title: Soma Livros
description: > # this means to ignore newlines until "baseurl:"
  Somos um sebo virtual desde 2017. Nossas transações são feitas na cidade de Birigui, interior de São Paulo.
baseurl: "/somalivros1" # the subpath of your site, e.g. /blog
url: "https://aarrigo.github.io/somalivros1/" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: white # Or use dark
markdown: kramdown
plugins:
  - jekyll-seo-tag

# Profile information
name: Soma Livros
tagline: livros semi novos, usados e fora de estoque.
about-description: Somos um sebo virtual desde 2017. Nossas transações são feitas na cidade de Birigui, interior de São Paulo. Para saber os livros que compramos e os que não compramos, <a href="quem-somos">clique aqui</a>. 
pic: 79.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: somalivros@gmail.com # Add your Email address
phone: 18 99182 0260 # Add your Phone number
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: # Add your Github handle
twitter: # Add your Twitter handle
estantevirtual: somalivros
skoob: somalivros
amazon: somalivros
instagram: somalivros
facebook: somalivros
listalivros: https://listium.com/@somalivros/42197/acervo-soma-livros


# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]

theme: jekyll-theme-cayman
