title: Soma Livros
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/somalivros1" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: white # Or use dark

# Profile information
name: Soma Livros
tagline: livros semi novos, usados e fora de estoque.
about-description: Somos um sebo virtual desde 2017. Nossas transações são feitas na cidade de Birigui, interior de São Paulo. Para saber os livros que compramos e os que não compramos, [clique aqui](https://aarrigo.github.io/somalivros1/quem-somos/).
pic: 79.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: somalivros@gmail.com # Add your Email address
phone: 18 99182 0260 # Add your Phone number
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: # Add your Github handle
twitter: # Add your Twitter handle
estante virtual:
skoob: somalivros
amazon: somalivros
instagram: somalivros
facebook: somalivros


# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]

theme: jekyll-theme-cayman
